### ISSUE TITLE
Compilation error - cannot open source file "amd_internal.h"

### ISSUE THREAD

**Issue by prehensilecode** [igraph/rigraph#325]
Trying to build with R 3.5.2 using Intel compilers version 2018.1. Used devtools to build: `devtools::install_github("igraph/rigraph")`. The following error occurred: 

```
ifort  -fopenmp -fpic  -O3 -xHost  -c AMD/Source/amd.f -o AMD/Source/amd.o
icc -std=gnu99 -I"/home/dwc62/lib64/R/include" -DNDEBUG   -I/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/include  -fopenmp -fpic  -O3 -xHost  -c AMD/Source/amd_1.c -o AMD/Source/amd_1.o
AMD/Source/amd_1.c(27): catastrophic error: cannot open source file "amd_internal.h"
  #include "amd_internal.h"
                           ^

compilation aborted for AMD/Source/amd_1.c (code 4)
make: *** [AMD/Source/amd_1.o] Error 4
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/dwc62/lib64/R/library/igraph’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/Rtmp6VxJE7/file28617fc6183f/igraph_1.1.0.tar.gz’ had non-zero exit status
```

The same error occurs when using `install.packages("igraph")`

Also tried manually cloning the repo, and then running "make" inside the local repo. That created the file `igraph_1.1.2.9000.tar.gz` which did include AMD (and other SuiteSparse code, like CHOLMOD, etc.). However, attempting to build using

```
install.packages("igraph_1.1.2.9000.tar.gz", repo = NULL, type = "source")
```

also fails with the same error:

```
** libs
ifort  -fopenmp -fpic  -O3 -xHost  -c AMD/Source/amd.f -o AMD/Source/amd.o
icc -std=gnu99 -I"/home/dwc62/lib64/R/include" -DNDEBUG   -I/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/include  -fopenmp -fpic  -O3 -xHost  -c AMD/Source/amd_1.c -o AMD/Source/amd_1.o
AMD/Source/amd_1.c(27): catastrophic error: cannot open source file "amd_internal.h"
  #include "amd_internal.h"
                           ^

compilation aborted for AMD/Source/amd_1.c (code 4)
make: *** [AMD/Source/amd_1.o] Error 4
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/dwc62/lib64/R/library/igraph’
Warning message:
In install.packages("igraph_1.1.2.9000.tar.gz", repo = NULL, type = "source") :
  installation of package ‘igraph_1.1.2.9000.tar.gz’ had non-zero exit status
```

**Comment by griznog** [comment]
I'm running into the same problem under both 3.5.2 and 3.6.0 with several versions of gcc:

```
* installing *source* package ‘igraph’ ...
** package ‘igraph’ successfully unpacked and MD5 sums checked
checking for gcc... gcc -m64 -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 -std=gnu99 accepts -g... yes
checking for gcc -m64 -std=gnu99 option to accept ISO C89... none needed
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran -m64 accepts -g... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 accepts -g... yes
checking how to run the C++ preprocessor... g++ -m64 -E
checking for rintf... yes
checking for finite... yes
checking for expm1... yes
checking for rint... yes
checking for log2... yes
checking for logbl... yes
checking for snprintf... yes
checking for log1p... yes
checking for round... yes
checking for fmin... yes
checking for stpcpy... yes
checking how to run the C preprocessor... gcc -m64 -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether stpcpy is declared... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking net/if.h usability... yes
checking net/if.h presence... yes
checking for net/if.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking net/if_dl.h usability... no
checking net/if_dl.h presence... no
checking for net/if_dl.h... no
checking sys/sockio.h usability... no
checking sys/sockio.h presence... no
checking for sys/sockio.h... no
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking for struct sockaddr.sa_len... no
checking for xml2-config... /scg/apps/software/scanpy/1.4.3/bin/xml2-config
checking for xmlSAXUserParseFile in -lxml2... yes
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
checking for __gmpz_add in -lgmp... yes
checking gmp.h usability... yes
checking gmp.h presence... yes
checking for gmp.h... yes
checking for glp_read_mps in -lglpk... yes
checking glpk.h usability... yes
checking glpk.h presence... yes
checking for glpk.h... yes
configure: creating ./config.status
config.status: creating src/Makevars.tmp
config.status: creating src/Makevars
config.status: creating src/config.h
** libs
gfortran -m64   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/lib64/gfortran/modules  -c AMD/Source/amd.f -o AMD/Source/amd.o
Warning: Nonconforming tab character in column 1 of line 422
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -march=x86-64 -mtune=generic   -fpic  -march=x86-64 -mtune=generic   -c AMD/Source/amd_1.c -o AMD/Source/amd_1.o
AMD/Source/amd_1.c:27:26: fatal error: amd_internal.h: No such file or directory
 #include "amd_internal.h"
                          ^
compilation terminated.
make: *** [AMD/Source/amd_1.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/griznog/.R/x86_64-redhat-linux-gnu-library/3.5/igraph’

The downloaded source packages are in
	‘/tmp/RtmpuVi1J2/downloaded_packages’
Warning message:
In install.packages("igraph") :
  installation of package ‘igraph’ had non-zero exit status

```
If I manually start copying the missing header files from the igraph source to a place in the include path, it will get past each successive missing file until I get to 

```
CHOLMOD/Partition/cholmod_camd.c:42:10: fatal error: camd.h: No such file or directory
 #include "camd.h"
          ^~~~~~~~
compilation terminated.
make: *** [CHOLMOD/Partition/cholmod_camd.o] Error 1
ERROR: compilation failed for package ‘igraph’
```

with `camd.h` not being in the igraph source.

**Comment by griznog** [comment]
My problem turned out to be self-inflicted, in my ~/R/Makevars I had: 

```
PKG_CFLAGS = -march=x86-64 -mtune=generic
PKG_CXXFLAGS = -march=x86-64 -mtune=generic
```

Which for some packages (igraph included) breaks the package CFLAGS/CXXFLAGS. Changing this to 

```
PKG_CFLAGS += -march=x86-64 -mtune=generic
PKG_CXXFLAGS += -march=x86-64 -mtune=generic
```

Solved the issue for me for this and several other packages (RcppArmadillo being the one where I finally figured this out.)

**Comment by ntamas** [comment]
`AMD` is not part of the source distribution any more so closing this.
