### ISSUE TITLE
Error in updating the package

### ISSUE THREAD

**Issue by sammo3182** [igraph/rigraph#259]
I got an error when updating the package from 1.1.2 to 1.2.1 through Rstudio in Windows 10 as following:

```
In file included from feedback_arc_set.c:31:0:
igraph_glpk_support.h:36:18: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
                  ^
compilation terminated.
make: *** [feedback_arc_set.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "D:/R/R-stable/etc/x64/Makeconf" -f "D:/R/R-stable/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="igraph.dll" SHLIB_LIBADD='$(FLIBS)' WIN=64 TCLBIN=64 ' had status 2
ERROR: compilation failed for package 'igraph'
```

I've manually installed glpk and set the PATH. Here's the info of my system environment:

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
```

**Comment by gaborcsardi** [comment]
You can wait until CRAN updates the binary package, or if you need it urgently, you can download it from here: https://win-builder.r-project.org/z2yQjuG2NT37/ (this link will be removed in 1-2 days)

**Comment by wlandau** [comment]
Those who need `igraph` in AppVeyor can [set `PKGTYPE: binary` in `appveyor.yml`](https://github.com/ropensci/drake/commit/8ff863f6649cc35d4e57c3369bf5c663247dc955). Solved a related issue for me.

**Comment by domi84** [comment]
Hello,
I needed to update some packages and now I cannot install igraph anymore,
Not sure it's exactly the same error

```
igraph_glpk_support.h:36:18: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
                  ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-36~1.3/etc/i386/Makeconf:208: feedback_arc_set.o] Error 1      
ERROR: compilation failed for package 'igraph'
* removing 'C:/Users/Domenico/OneDrive/Documents/R/win-library/3.6/igraph'
* restoring previous 'C:/Users/Domenico/OneDrive/Documents/R/win-library/3.6/igraph'      

The downloaded source packages are in
        'C:\Users\Domenico\AppData\Local\Temp\RtmpWEVEwp\downloaded_packages'
Warning message:
In install.packages("igraph") :
  installation of package 'igraph' had non-zero exit status
```
```

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3 
```

**Comment by szhorvat** [comment]
@domi84 Try installing as `install.packages('igraph, type='binary')`. For support requests (as opposed to bug reports), please consider using https://igraph.discourse.group/ in the future.

**Comment by vtraag** [comment]
@domi84 for more information, at the moment, the recently released version 1.2.5 of the R interface for `igraph` does not yet have binaries for Windows (also mentioned [here](https://github.com/igraph/rigraph/issues/377#issuecomment-602586819)). Normally, R tries to install the latest version, and if there is no binary available, it will try to compile the package for you (which fails under Windows, as you have noticed). By forcing a binary installation, as @szhorvat suggests, R will install version 1.2.4.2.

**Comment by domi84** [comment]
Thanks.
Sorry for the newbie issue.
